site_name: 星舟Starship
site_url: https://howcam.github.io/
site_author: Starship Dev Team
edit_uri: edit/main/docs/

repo_url: https://github.com/howcam/howcam.github.io/
repo_name: HowCam/howcam.github.io

copyright: Copyright &copy; 2024 <a href='https://github.com/orgs/Starship-Dev-Team/people'> Starship Dev Team </a>

extra:
  social:
  - icon: octicons/mail-24
    link: mailto:hownotfound@gmail.com
  - icon: fontawesome/brands/github
    link: https://github.com/orgs/Starship-Dev-Team/people

nav:
  - 首页: 
    - 首页: index.md
    - 贡献指南: intro/contribute.md
    - 格式手册: intro/format.md
    - 数学符号表: intro/symbol.md
    - 如何使用GitHub: intro/how-to-use-GitHub.md
    - Markdown扫盲: intro/Markdown.md
    - 加入我们: intro/join-us.md
  - 语文:
    - 语文部分简介: Chinese/Chinese-intro.md
    - 语文笔记: Chinese/notes.md
    - 名著专项:
      - 西游记: Chinese/Journey-to-the-West.md
      - 朝花夕拾: Chinese/Dawn-Blossoms-Plucked-at-Dusk.md
      - 水浒传: Chinese/Water-Margin.md
      - 儒林外史: Chinese/The-Scholars.md
      - 骆驼祥子: Chinese/Xiang-zi.md
      - 钢铁是怎样炼成的: Chinese/Kak-zakalyalas-stal.md
      - 昆虫记: Chinese/Souvenirs-entomologiques.md
      - 艾青诗选: Chinese/Selected-Poems-of-Ai-Qing.md
      - 海底两万里: Chinese/Twenty-Thousand-Leagues-Under-the-Sea.md
    - 作文专项:
      - 分类作文集锦:
        - 成长篇: Chinese/model-essay/growth.md
        - 亲情篇: Chinese/model-essay/family.md
        - 传统文化类: Chinese/model-essay/Traditional-Culture.md
      - 作文集锦:
        - 我的青春里有一缕清香: Chinese/model-essay/我的青春里有一缕清香.md
        - 终于找到答案: Chinese/model-essay/终于找到答案.md
        - ___＿小天地大: Chinese/model-essay/___＿小天地大.md
        - 青春要有一颗滚烫的心: Chinese/model-essay/青春要有一颗滚烫的心.md
        - 那一抹中国红: Chinese/model-essay/那一抹中国红.md
        - 那堂特别的语文课: Chinese/model-essay/那堂特别的语文课.md
        - 《》让我学会＿_: Chinese/model-essay/《》让我学会＿_.md
        - 不止一次，我＿: Chinese/model-essay/不止一次，我＿.md
        - 冬日也是春: Chinese/model-essay/冬日也是春.md
        - 守护＿_: Chinese/model-essay/守护＿_.md
      - 2024中考作文押题: Chinese/model-essay/2024语文中考作文押题.md
      - 高分作文集: Chinese/model-essay/高分作文集.md
    - 文言文专项:
      - 文言文知识: Chinese/Classic-Chinese.md
  - 数学:
    - 数学部分简介: math/math-intro.md
    - 2017CMO-4: math/2017CMO-4.md
    - 2019CMO-2: math/2019CMO-2.md
    - 一道奇怪的题: math/AStrangeProblem.md
  - 历史:
    - 历史部分简介: history/history-intro.md
    - 初中部分:
      - 九年级历史资料: history/grade-9.md
      - 历史速查表格:
        - 七年级: history/grade-7-form.md
        - 八年级: history/grade-8-form.md
        - 九年级: history/grade-9-form.md
    - 高中部分:
      - 中国古代政治制度: history/political-system-of-ancient-China.md
  - 政治:
    - 政治部分简介: politics/politics-intro.md
    - 九年级政治资料: politics/grade-9.md
    - 高中部分:
      - 政治必修一: politics/BX-1.md
  - 化学:
    - 化学部分简介: chemistry/chemistry-intro.md
    - 初中化学笔记: chemistry/notes.md
    - 分章节讲稿:
      - 初中化学:
        - U0 绪言 化学使世界变得更加绚丽多彩: chemistry/U0.md
        - U1 走进化学世界: chemistry/U1.md
  - 物理:
    - 物理部分简介: physics/physics-intro.md
    - 分章节讲稿:
      - 初中部分:
        - U1 机械运动: physics/junior/U1.md
        - U2 声现象: physics/junior/U2.md
      - 高中部分:
        - U1 运动的描述: physics/senior/U1.md
  - 生物:
    - 生物部分简介: biology/biology-intro.md
    - 高中部分:
      - U1 走近细胞: biology/senior/U1.md
      - 生物必修一: biology/senior/BX-1.md

theme:
  name: material
  language: zh
  favicon: images/favicon.png
  icon:
    logo: material/ufo-outline
  features:
    - content.action.edit
    - content.action.view
    - content.editable
    - content.revision
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.footer
    - navigation.tracking
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - toc.follow # 目录跟踪-页面右侧的小目录
    - content.footnote.tooltips # 脚注提示工具（悬停显示）
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到暗夜模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: 切换到日间模式

plugins:
  - search
  - git-committers:
      repository: HowCam/howcam.github.io
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true

markdown_extensions:
  - footnotes # 脚注
  - attr_list
  - admonition
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://jsd.cdn.zzko.cn/npm/mathjax@3/es5/tex-chtml.js
      
extra_css:
  - style/extra.css
  - https://jsd.cdn.zzko.cn/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css